// AUTHENTICATION TYPES
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// YELP TYPES
export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const GET_RESTAURANT_DETAILS = 'GET_RESTAURANT_DETAILS';
export const RANDOM_RESTAURANT = 'RANDOM_RESTAURANT';
export const GET_LOCATION = 'GET_LOCATION';
export const LOCATION_ERROR = 'LOCATION_ERROR';
export const CLEAR_RESTAURANT = 'CLEAR_RESTAURANT';
export const SET_LOADING = 'SET_LOADING';

// FILTER TYPES
export const ADD_FILTERS = 'ADD_FILTERS';
export const GET_FILTERS = 'GET_FILTERS';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const FILTER_ERROR = 'FILTER_ERROR';

// ALERT TYPES
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
